prefix skos:    <http://www.w3.org/2004/02/skos/core#>
ASK WHERE{
{	
	SELECT ?matchPrefAndAltLabels  ?matchPrefAndHiddenLabels ?matchAltAndHiddenLabels WHERE{
		?concept a skos:Concept.
				 {
					SELECT (count(?prefLabel) as ?matchPrefAndAltLabels)  WHERE{
							?concept skos:prefLabel ?prefLabel.
					   
					  	    {
						 	  SELECT  * WHERE{
								?concept skos:altLabel ?altLabel.
								
						 	 } 
						 }
						 FILTER (?altLabel = ?prefLabel).
					 }
				  }
				  
				  {
				
					SELECT   (count(?prefLabel) as ?matchPrefAndHiddenLabels)  WHERE{
							?concept skos:prefLabel ?prefLabel.
					   
					  	    {
						 	  SELECT  * WHERE{
								?concept skos:hiddenLabel ?hiddenLabel.
								
						 		 } 
							 }
						 FILTER (?hiddenLabel = ?prefLabel).
					 }
					 
				 }
				 
				 
				  {
					 	SELECT  (count(?altLabel) as ?matchAltAndHiddenLabels) WHERE{
							?concept skos:altLabel ?altLabel.
					   
					  	    {
						 	  SELECT  * WHERE{
								?concept skos:hiddenLabel ?hiddenLabel.
								
						 	 } 
						 }
						 FILTER (?hiddenLabel = ?altLabel).
						}
					}
					
	}
	
	}
	FILTER( (?matchPrefAndAltLabels+?matchPrefAndHiddenLabels+?matchAltAndHiddenLabels)=0).

}