prefix skos:    <http://www.w3.org/2004/02/skos/core#>
ASK WHERE{
	{	SELECT (count(distinct ?another) AS ?result)  WHERE{
		 ?concept a skos:Concept.
		 ?scheme skos:hasTopConcept ?concept.
		 ?concept skos:broader ?anotherConcept.
		 OPTIONAL{
		 	?anotherConcept skos:inScheme ?scheme.
		 }
		}
	}
	FILTER (?result <= 1)
}

