prefix skos:    <http://www.w3.org/2004/02/skos/core#>

#A concept A cannot be broader of itself
ask where{
	{
	SELECT (count (?concept) as ?nconcepts) WHERE{
	 ?concept a skos:Concept.
	 OPTIONAL {
		?concept skos:broader ?broader.
	 }
	 FILTER (bound(?broader) && ?broader = ?concept).
	}
	}
 FILTER (?nconcepts=0).
}