prefix skos:    <http://www.w3.org/2004/02/skos/core#>

#If a concept A has a closeMatch B, B cannot be exactMatch
ask where{
	{
	SELECT (count (?concept) as ?nconcepts) WHERE{
	 ?concept a skos:Concept.
	 ?concept skos:exactMatch ?match.
	 FILTER NOT EXIST {?concept ?skos:closeMatch ?match}.
	 FILTER NOT EXIST {?concept ?skos:relatedMatch ?match}.
	}
	}
 FILTER (?nconcepts=0).
}