prefix skos:    <http://www.w3.org/2004/02/skos/core#>

#If a concept A has a broaderTransitive B, B cannot be related to A
ASK WHERE{
{
	SELECT (count (?concept) as ?nconcepts) WHERE{
			 ?concept a skos:Concept.
			 ?concept skos:related ?related.
			 OPTIONAL{
				?related skos:related ?otherRelated.
			}
			FILTER (bound (?otherRelated)).
		    FILTER NOT EXISTS { ?related skos:related ?otherRelated}.
	}
}

	FILTER (?nconcepts=0).
}
