prefix skos:    <http://www.w3.org/2004/02/skos/core#>

#If a concept A has a broader B, B cannot have A as broader
ask where{
	{
	SELECT (count (?concept) as ?nconcepts) WHERE{
	 ?concept a skos:Concept.
	 ?concept skos:broader ?broader.
	 OPTIONAL {
		?broader skos:broader ?otherBroader.
	 }
	 FILTER (?otherBroader = ?concept).
	}
	}
 FILTER (?nconcepts=0).
}