prefix skos:    <http://www.w3.org/2004/02/skos/core#>

#If a concept A has an hierarchy relationshiop with B, B cannot be related to A

ASK WHERE{
	{
	SELECT (count (?concept) as ?nconcepts) WHERE{
		 ?concept a skos:Concept.
		 ?concept ?psemantic ?related.
		 FILTER (?psemantic in (skos:broader, skos:narrower, skos:broaderTransitive, skos:narrowerTransitive)).
		 OPTIONAL {
			?concept skos:related ?otherRelated.
		 }
		 FILTER (?related = ?otherRelated).
		}
	}
	FILTER (?nconcepts=0).
}
 