prefix skos:    <http://www.w3.org/2004/02/skos/core#>

#If a concept A has a broader B, B cannot be narrower of A

ASK WHERE{
	{
	SELECT (count (?concept) as ?nconcepts) WHERE{
		 ?concept a skos:Concept.
		 ?concept skos:broader ?broader.
		 OPTIONAL {
			?concept skos:narrower ?narrower.
		 }
		 FILTER (bound(?broader) && bound(?narrower) && ?broader = ?narrower).
		}
	}
	FILTER (?nconcepts=0).
}
 