prefix skos:    <http://www.w3.org/2004/02/skos/core#>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (COUNT(?label) AS ?no) { 
	?concept rdf:type skos:Concept. 
	?concept skos:prefLabel ?label.
}